#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""ISD package extras config (.isdconfig) — stdlib only.

Commands: defconfig | show | set KEY=VAL | validate | menu
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CFG = ROOT / ".isdconfig"

# Always-on core (cannot be disabled).
FORBIDDEN_DISABLE = ("BUSYBOX", "RUNIT")

# Optional extras selectable via .isdconfig / menu.
EXTRAS = ("NANO", "NCURSES", "OPENDOAS", "TINYCC", "GNUMAKE", "DOOM")

# Not yet packaged — require packages/<dir>/ before enabling.
FUTURE_PACKAGES = {
    "TINYCC": "tinycc",
    "GNUMAKE": "gnumake",
    "DOOM": "doom",
}

# If KEY=y, ensure each dep is y (or reject).
AUTO_DEPS = {
    "NANO": ("NCURSES",),
}

CORE_DEFAULTS = {k: "y" for k in FORBIDDEN_DISABLE}
EXTRA_DEFAULTS = {k: "n" for k in EXTRAS}


def cfg_path(explicit: str | None = None) -> Path:
    if explicit:
        return Path(explicit)
    env = os.environ.get("ISD_CONFIG")
    if env:
        return Path(env)
    return DEFAULT_CFG


def parse_cfg(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.is_file():
        return data
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, val = line.split("=", 1)
        data[key.strip()] = val.strip()
    return data


def write_cfg(path: Path, data: dict[str, str]) -> None:
    keys = [f"CONFIG_PKG_{k}" for k in FORBIDDEN_DISABLE] + [
        f"CONFIG_PKG_{k}" for k in EXTRAS
    ]
    lines = [
        "# ISD package extras (.isdconfig) — generated by scripts/isdconfig.py",
        "# Profile packages.txt remains the mandatory set; this file adds/overrides extras.",
        "",
    ]
    for key in keys:
        short = key[len("CONFIG_PKG_") :]
        val = data.get(key, CORE_DEFAULTS.get(short, EXTRA_DEFAULTS.get(short, "n")))
        lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_defaults(data: dict[str, str]) -> dict[str, str]:
    out = dict(data)
    for k, v in CORE_DEFAULTS.items():
        out.setdefault(f"CONFIG_PKG_{k}", v)
    for k, v in EXTRA_DEFAULTS.items():
        out.setdefault(f"CONFIG_PKG_{k}", v)
    return out


def pkg_enabled(data: dict[str, str], short: str) -> bool:
    return data.get(f"CONFIG_PKG_{short}", "n").lower() in ("y", "yes", "1")


def cmd_defconfig(path: Path, force: bool) -> int:
    if path.is_file() and not force:
        print(f"  CONFIG    {path} already present (use --force to reset)")
        return 0
    data = ensure_defaults({})
    write_cfg(path, data)
    print(f"  CONFIG    wrote {path}")
    return 0


def cmd_show(path: Path) -> int:
    data = ensure_defaults(parse_cfg(path))
    print(f"# {path}")
    for k in list(FORBIDDEN_DISABLE) + list(EXTRAS):
        key = f"CONFIG_PKG_{k}"
        print(f"{key}={data.get(key, 'n')}")
    return 0


def cmd_set(path: Path, assignments: list[str]) -> int:
    data = ensure_defaults(parse_cfg(path))
    for item in assignments:
        if "=" not in item:
            print(f"✗ expected KEY=VAL, got {item!r}", file=sys.stderr)
            return 1
        key, val = item.split("=", 1)
        key = key.strip()
        val = val.strip().lower()
        if not key.startswith("CONFIG_PKG_"):
            key = f"CONFIG_PKG_{key}"
        short = key[len("CONFIG_PKG_") :].upper()
        key = f"CONFIG_PKG_{short}"
        if val not in ("y", "n"):
            print(f"✗ value must be y or n: {item}", file=sys.stderr)
            return 1
        if short in FORBIDDEN_DISABLE and val == "n":
            print(f"✗ cannot disable CONFIG_PKG_{short} (core package)", file=sys.stderr)
            return 1
        data[key] = val
        if val == "y" and short in AUTO_DEPS:
            for dep in AUTO_DEPS[short]:
                data[f"CONFIG_PKG_{dep}"] = "y"
    write_cfg(path, data)
    print(f"  CONFIG    updated {path}")
    return 0


def cmd_validate(path: Path, profile: str) -> int:
    data = ensure_defaults(parse_cfg(path))
    errors: list[str] = []

    for short in FORBIDDEN_DISABLE:
        if not pkg_enabled(data, short):
            errors.append(
                f"✗ CONFIG_PKG_{short}=n is forbidden (core package; "
                f"leave CONFIG_PKG_{short}=y)."
            )

    for short, deps in AUTO_DEPS.items():
        if pkg_enabled(data, short):
            for dep in deps:
                if not pkg_enabled(data, dep):
                    errors.append(
                        f"✗ CONFIG_PKG_{short}=y requires CONFIG_PKG_{dep}=y "
                        f"(auto-dep)."
                    )

    for short, dirname in FUTURE_PACKAGES.items():
        if not pkg_enabled(data, short):
            continue
        pkg_dir = ROOT / "packages" / dirname
        if not pkg_dir.is_dir() or not (pkg_dir / "build.sh").is_file():
            errors.append(
                f"✗ CONFIG_PKG_{short}=y but packages/{dirname}/ is not packaged yet.\n"
                f"  Leave CONFIG_PKG_{short}=n, or add packages/{dirname}/ "
                f"(build.sh + metadata).\n"
                f"  Interim (legacy IR0 inject): "
                f"IR0_LEGACY_USERSPACE=1 make load-userspace-devtools"
            )
        if short == "DOOM":
            iwad = os.environ.get("ISD_DOOM_IWAD", "").strip()
            if not iwad or not Path(iwad).is_file():
                errors.append(
                    "✗ CONFIG_PKG_DOOM=y requires ISD_DOOM_IWAD pointing to an "
                    "existing IWAD file."
                )

    # Known extras must map to a recipe when enabled (non-future).
    for short in EXTRAS:
        if short in FUTURE_PACKAGES:
            continue
        if not pkg_enabled(data, short):
            continue
        dirname = short.lower()
        pkg_dir = ROOT / "packages" / dirname
        if not pkg_dir.is_dir():
            errors.append(f"✗ CONFIG_PKG_{short}=y but packages/{dirname}/ missing.")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    print(f"✓ isdconfig validate OK PROFILE={profile}")
    return 0


def cmd_menu(path: Path) -> int:
    data = ensure_defaults(parse_cfg(path))
    print("ISD extras (toggle y/n). Core busybox/runit are always on.")
    print(f"Config: {path}")
    print("")
    for short in EXTRAS:
        key = f"CONFIG_PKG_{short}"
        cur = data.get(key, "n")
        note = ""
        if short in FUTURE_PACKAGES:
            note = f"  [future: packages/{FUTURE_PACKAGES[short]}/]"
        if short in AUTO_DEPS:
            note += f"  [deps: {', '.join(AUTO_DEPS[short])}]"
        print(f"  {key}={cur}{note}")
    print("")
    print("Non-interactive: scripts/isdconfig.py set CONFIG_PKG_NANO=y")
    print("Validate:        scripts/isdconfig.py validate")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="ISD .isdconfig helper")
    ap.add_argument(
        "--config",
        default=None,
        help="path to .isdconfig (default: $ISD_CONFIG or repo root)",
    )
    ap.add_argument(
        "--profile",
        default=os.environ.get("PROFILE", "minimal"),
        help="profile name for validate messages",
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_def = sub.add_parser("defconfig", help="write defaults if missing")
    p_def.add_argument(
        "--force", action="store_true", help="overwrite existing config"
    )

    sub.add_parser("show", help="print effective config")
    p_set = sub.add_parser("set", help="set CONFIG_PKG_*=y|n")
    p_set.add_argument("assignments", nargs="+", help="KEY=VAL …")
    sub.add_parser("validate", help="validate config against recipes")
    sub.add_parser("menu", help="list extras (non-interactive help)")

    args = ap.parse_args(argv)
    path = cfg_path(args.config)

    if args.cmd == "defconfig":
        return cmd_defconfig(path, args.force)
    if args.cmd == "show":
        return cmd_show(path)
    if args.cmd == "set":
        return cmd_set(path, args.assignments)
    if args.cmd == "validate":
        return cmd_validate(path, args.profile)
    if args.cmd == "menu":
        return cmd_menu(path)
    ap.error(f"unknown command {args.cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
